### ISSUE TITLE
Rails4 - Two rspec tests fail in rails4 branch

### ISSUE THREAD

**Issue by YusiFan** [MarkUsProject/Markus#1923]
```
Failures:

  1) Assignment custom validations fails when due_date is invalid
     Failure/Error: assignment = build(:assignment, due_date: '2000/01/40')
     ArgumentError:
       argument out of range
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activesupport-4.1.8/lib/active_support/values/time_zone.rb:289:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activesupport-4.1.8/lib/active_support/values/time_zone.rb:289:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activesupport-4.1.8/lib/active_support/values/time_zone.rb:289:in `parse'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activesupport-4.1.8/lib/active_support/core_ext/string/zones.rb:9:in `in_time_zone'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activerecord-4.1.8/lib/active_record/attribute_methods/time_zone_conversion.rb:37:in `due_date='
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `public_send'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/strategy/build.rb:9:in `result'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/activesupport-4.1.8/lib/active_support/notifications.rb:161:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.1.2@markus/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/assignment_spec.rb:83:in `block (3 levels) in <top (required)>'

  2) Assignment#latest_due_date when SectionDueDates are enabled and a SectionDueDate has the latest due date returns the due date of that SectionDueDate
     Failure/Error: expect(@assignment.latest_due_date).to eq @section_due_date.due_date
       
       expected: 2014-12-04 15:56:09.332327345 -0500
            got: 2014-12-04 15:56:09.332327000 -0500
       
       (compared using ==)
       
       Diff:
       
     # ./spec/models/assignment_spec.rb:735:in `block (5 levels) in <top (required)>'

Finished in 16.65 seconds (files took 7.93 seconds to load)
353 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/models/assignment_spec.rb:82 # Assignment custom validations fails when due_date is invalid
rspec ./spec/models/assignment_spec.rb:734 # Assignment#latest_due_date when SectionDueDates are enabled and a SectionDueDate has the latest due date returns the due date of that SectionDueDate
```

**Comment by tsimica** [comment]
The first issue is related to time inconsistencies within RSpec and the database. More can be read around here: http://stackoverflow.com/questions/3559924/rails-time-inconsistencies-with-rspec

I've added a custom RSpec matcher to check if the dates are equal to within milliseconds.

**Comment by tsimica** [comment]
The first issue results in a failure because Rails automatically converts the string input to datetime without running the Date_Validator on the string itself. The way I concluded this was because of setting a debugger in the actual validator and controller and found that the debugger points were not being executed.

**Comment by david-yz-liu** [comment]
@tsimica I'm okay removing the first test; we can check invalid date inputs in the controller test (later).

**Comment by tsimica** [comment]
For issue #1, when building an assignment with an invalid date, the exception is thrown immediately. This means that even we try to handle the error gracefully (i.e. begin...rescue) the program already terminates. 

Solution: Discussed removing this test case. Also consider sanitation of input occurring when received and not on creation.
