### ISSUE TITLE
IOErrors from git_repositories.rb tests

### ISSUE THREAD

**Issue by akbiggs** [MarkUsProject/Markus#2126]
When I run the specs, five tests fail, each from git_repositories.rb. Should we be deleting any existing test_repo folder from the test repos data folder before the test attempts to create a new one? 

```
  1) Repository::GitRevision with a git repo #files_at_path retrieves an object with the same name from the repo
     Failure/Error: let!(:repo) { build(:git_repository) }
     IOError:
       Could not create a repository at /home/vagrant/Markus/data/test/repos/test_repo:
                                 some directory with same name exists already
     # ./lib/repo/git_repository.rb:61:in `create'
     # ./spec/factories/git_repositories.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/repo/git_revision_spec.rb:6:in `block (3 levels) in <top (required)>'

  2) Repository::GitRevision with a git repo #files_at_path retrieves an object of type Repository::RevisionFile
     Failure/Error: let!(:repo) { build(:git_repository) }
     IOError:
       Could not create a repository at /home/vagrant/Markus/data/test/repos/test_repo:
                                 some directory with same name exists already
     # ./lib/repo/git_repository.rb:61:in `create'
     # ./spec/factories/git_repositories.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/repo/git_revision_spec.rb:6:in `block (3 levels) in <top (required)>'

  3) Repository::GitRevision with a git repo #stringify gets the correct file data
     Failure/Error: let!(:repo) { build(:git_repository) }
     IOError:
       Could not create a repository at /home/vagrant/Markus/data/test/repos/test_repo:
                                 some directory with same name exists already
     # ./lib/repo/git_repository.rb:61:in `create'
     # ./spec/factories/git_repositories.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/repo/git_revision_spec.rb:6:in `block (3 levels) in <top (required)>'

  4) Repository::GitRevision with a git repo #directories_at_path retrieves an object with the same name from the repo
     Failure/Error: let!(:repo) { build(:git_repository) }
     IOError:
       Could not create a repository at /home/vagrant/Markus/data/test/repos/test_repo:
                                 some directory with same name exists already
     # ./lib/repo/git_repository.rb:61:in `create'
     # ./spec/factories/git_repositories.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/repo/git_revision_spec.rb:6:in `block (3 levels) in <top (required)>'

  5) Repository::GitRevision with a git repo #directories_at_path retrieves an object of type Repository::RevisionDirectory
     Failure/Error: let!(:repo) { build(:git_repository) }
     IOError:
       Could not create a repository at /home/vagrant/Markus/data/test/repos/test_repo:
                                 some directory with same name exists already
     # ./lib/repo/git_repository.rb:61:in `create'
     # ./spec/factories/git_repositories.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/repo/git_revision_spec.rb:6:in `block (3 levels) in <top (required)>'
```

**Comment by SoftwareDev** [comment]
You usually don't have to. Just confirming which branch you are on? The Git branch requires some additional setup for gitolite but I have a feeling you're on master.

**Comment by akbiggs** [comment]
Yup, I'm on master.

**Comment by SoftwareDev** [comment]
I have a feeling that this is an individual setup issue since some recent builds have those tests passing. https://travis-ci.org/MarkUsProject/Markus/builds/59148046 I'll see if I can recreate but I've never seen this before while working with the git stuff.

**Comment by akbiggs** [comment]
Makes sense. Thanks!

**Comment by SoftwareDev** [comment]
Hmm, try adding this line `FileUtils.rm_rf(Dir["#{Rails.root}/data/test/repos/test_repo"])` after line 59 in Markus\spec\spec_helper.rb .. Might help

**Comment by akbiggs** [comment]
Doesn't help. Shouldn't that already be handled by the `config.after(:each) ...` block right before line 59 anyways?

**Comment by akbiggs** [comment]
Okay, so this issue was happening due to sharing my Markus folder between my Windows machine and my vagrant environment, so I could edit the codebase from my IDE. For some reason(investigating atm), this was preventing rm -rf from wiping out the .git folder within the test_repo directory, meaning the directory would not be removed between tests.

**Comment by david-yz-liu** [comment]
@akbiggs Sorry to hear you had trouble. I had thought that others in the past have successfully synced their folders, though perhaps not on Windows. Also not really sure why this would prevent the deletion of the .git folder.

As a side note, others have disabled sharing because it was thought to slow down the server to unbearable speeds.

At least one student this term used FTP to sync edits they made locally to the vagrant box.
