### ISSUE TITLE
Tests failing from master branch (rake test)

### ISSUE THREAD

**Issue by WChrisK** [MarkUsProject/Markus#2564]
Occurs with `rake test` and `rake test RAILS_ENV=test`

```
  1) Error:
AssignmentTest#test_: An Assignment with a students in groupings setup with marking complete (flexible marking) should be able to generate a detailed CSV report of flexible based marks (including criteria). :
ActiveRecord::RecordInvalid: Validation failed: Markable has already been taken
    test/unit/assignment_test.rb:494:in `block (5 levels) in <class:AssignmentTest>'
    test/unit/assignment_test.rb:493:in `block (4 levels) in <class:AssignmentTest>'
    test/unit/assignment_test.rb:486:in `block (3 levels) in <class:AssignmentTest>'


  2) Error:
AssignmentTest#test_: An Assignment with a students in groupings setup with marking complete (rubric marking) should be able to generate a detailed CSV report of rubrics based marks (including criteria). :
ActiveRecord::RecordInvalid: Validation failed: Markable has already been taken
    test/unit/assignment_test.rb:419:in `block (5 levels) in <class:AssignmentTest>'
    test/unit/assignment_test.rb:418:in `block (4 levels) in <class:AssignmentTest>'
    test/unit/assignment_test.rb:411:in `block (3 levels) in <class:AssignmentTest>'


  3) Error:
EnsureConfigHelperTest#test_: setting up the markus_configurator with a log dir with a repo dir with an executable that is not properly escaped should accept the configuration. :
RuntimeError: The setting automated_tests_REPOSITORY with path /home/vagrant/Markus/data/test is not writable. Please double check the setting in config/environments/test.rb
    app/helpers/ensure_config_helper.rb:51:in `check_in_writable_dir'
    app/helpers/ensure_config_helper.rb:26:in `check_config'
    test/unit/helpers/ensure_config_helper_test.rb:151:in `block (6 levels) in <class:EnsureConfigHelperTest>'
    test/unit/helpers/ensure_config_helper_test.rb:150:in `block (5 levels) in <class:EnsureConfigHelperTest>'


  4) Error:
EnsureConfigHelperTest#test_: setting up the markus_configurator with a log dir with a repo dir with an executable validate file should accept the configuration because all files and directories are ready. :
RuntimeError: The setting automated_tests_REPOSITORY with path /home/vagrant/Markus/data/test is not writable. Please double check the setting in config/environments/test.rb
    app/helpers/ensure_config_helper.rb:51:in `check_in_writable_dir'
    app/helpers/ensure_config_helper.rb:26:in `check_config'
    test/unit/helpers/ensure_config_helper_test.rb:105:in `block (6 levels) in <class:EnsureConfigHelperTest>'
    test/unit/helpers/ensure_config_helper_test.rb:104:in `block (5 levels) in <class:EnsureConfigHelperTest>'


  5) Error:
EnsureConfigHelperTest#test_: setting up the markus_configurator with a log dir with a repo dir with an executable validate file with an escaped space should accept the configuration because all files and directories are ready. :
RuntimeError: The setting automated_tests_REPOSITORY with path /home/vagrant/Markus/data/test is not writable. Please double check the setting in config/environments/test.rb
    app/helpers/ensure_config_helper.rb:51:in `check_in_writable_dir'
    app/helpers/ensure_config_helper.rb:26:in `check_config'
    test/unit/helpers/ensure_config_helper_test.rb:128:in `block (6 levels) in <class:EnsureConfigHelperTest>'
    test/unit/helpers/ensure_config_helper_test.rb:127:in `block (5 levels) in <class:EnsureConfigHelperTest>'

1397 runs, 3806 assertions, 0 failures, 5 errors, 0 skips
```

**Comment by david-yz-liu** [comment]
@WChrisK Thanks for pointing this out - I fixed the first two errors, but couldn't not replicate the bottom 3. This deepens my suspicion that it was a permission issue on your machine. We can look at it tomorrow.
