### ISSUE TITLE
MarkUs installation errors

### ISSUE THREAD

**Issue by bobthefairycat** [MarkUsProject/Markus#5733]
Following the instructions in the Wiki, https://github.com/MarkUsProject/Markus/wiki/Installation, here are some errors that occurred while trying to set up a new instance of MarkUs on a fresh machine:

1. Using Ruby 2.5, the `bundle install` command fails due to the version of action_policy required in `Gemfile.lock`

```
   action_policy-0.6.0 requires ruby version >= 2.6.0, which is incompatible with the current version, ruby 2.5.8p224
```

2. Finding the issue in (1), the following was done:
    - the cloned `Markus` directory was removed
    - `sudo apt purge ruby*`
    - `ruby2.7`, `ruby2.7-dev` were installed instead, and `ruby-svn` re-installed
However, when precompiling the rails assets using `RAILS_RELATIVE_URL_ROOT=... RAILS_ENV=production bundle exec rails i18n:js:export`, the following error is thrown:

```
rails aborted!
Config::Validation::Error: Config validation failed:

  validate_file: is missing
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config/validation/validate.rb:20:in `validate_using!'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config/validation/validate.rb:8:in `validate!'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config/options.rb:58:in `reload!'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config.rb:48:in `load_files'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config.rb:56:in `load_and_set_settings'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:11:in `preload'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `public_send'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `method_missing'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/application.rb:96:in `inherited'
/var/www/html/Markus/config/application.rb:14:in `<module:Markus>'
/var/www/html/Markus/config/application.rb:13:in `<top (required)>'
/var/www/html/Markus/Rakefile:5:in `require'
/var/www/html/Markus/Rakefile:5:in `<top (required)>'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/command.rb:50:in `invoke'
/var/www/html/Markus/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
```

Other information:
- Repo cloned: `git clone --single-branch --branch release-v1 https://github.com/MarkUsProject/Markus.git`
- Nodejs version: v12.22.8
- Yarn version: 1.22.17
- Bundler version 2.3.4
- Gem version 3.3.4
- Rails version 6.1.4.1

**Comment by mishaschwartz** [comment]
Thanks for the report. The error message is indicating that the `validate_file` configuration setting is missing. Please see the docs here for more information: https://github.com/MarkUsProject/Wiki/blob/release/Configuration.md
